### ISSUE TITLE
Video upload breaks at OAuth attempt, gives no URL

### ISSUE THREAD

**Issue by hspindell** [tokland/youtube-upload#17]
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlparse'

**Comment by tokland** [comment]
On issues report you should paste version (commit), full command, full output. It seems you are using python-six, a compatibility module. No idea how to solve this, but start from here: http://goo.gl/YZBtaW

**Comment by hspindell** [comment]
Noted, thank you. I will update it accordingly.

**Comment by tokland** [comment]
No feedback. Closing.

**Comment by AvdN** [comment]
This is an indirect effect of the oauth2client package (required by google-api-python-client that youtube-upload relies upon) requirements saying six>=1.6.1, but not working with six 1.9.0, I had to downgrade six to 1.6.1 to get this working again.

**Comment by tokland** [comment]
Thx for the info. Maybe you can open an issue? https://github.com/google/google-api-python-client/issues/
